;==============================================================================
; WiC64 Browser
;
; Browses programs, pictures and SID music served by the .NET server on a
; PC or Mac (see ../server) and loads them over the WiC64.
;
;   F1 / F3 / F5   programs / pictures / music
;   A-T            open the entry (folders and .d64 images open like folders)
;   SHIFT+A-T      save the program to disk (device 8)
;   INST/DEL       parent folder
;   + / -          next / previous page
;   RETURN         info about the playing tune (and back)
;   SPACE          next tune
;   1-9            select a subtune
;   F7 / RUN/STOP  stop music
;   F2             change the server address
;   <-             WiC64 portal (fetched through the server)
;
; While the menu is on screen the browser asks the server once a second
; whether something was pushed (make push or the web UI) and runs it.
;
; Memory map
;   $0100-$016f    starter: receives the end of a program over the browser, starts it
;   $0200-$0258    request header and URL (BASIC input buffer, unused)
;   $02a7-$02f6    message line, folder ids of the menu entries (unused area)
;   $0334-$03ff    standalone SID player or LOAD helper (sent by the server)
;   $0400-$07e7    menu screen (row 24 is the status line)
;   $0801-         BASIC stub that copies the code below to $c000
;   $0800-$cfff    programs are received to their load address, then saved and/or started
;   $0800-$bfff    free for SID tunes played in the background
;   $4400/$6000    picture screen RAM / bitmap (VIC bank 1)
;   $c000-$cfff    this program
;   $d000-$d4ff    copy of the startup code, in the RAM under the I/O area (for F2)
;
; The browser avoids zeropage, so SID tunes can use any zeropage location.
;==============================================================================

!cpu 6502

!src "wic64.h"
!src "config.asm"                       ; generated by the Makefile: proposed server address

GETIN           = $ffe4
SETLFS          = $ffba
SETNAM          = $ffbd
OPEN            = $ffc0
CLOSE           = $ffc3
CHKIN           = $ffc6
CHKOUT          = $ffc9
CLRCHN          = $ffcc
CHRIN           = $ffcf
CHROUT          = $ffd2
SAVE            = $ffd8
CINT            = $ff81
IOINIT          = $ff84
RESTOR          = $ff8a
KERNAL_IRQ      = $ea31
BASIC_CLR       = $a659                 ; reset the text pointer and CLR
BASIC_RUN       = $a7ae                 ; execute the program

KEY_F1          = $85
KEY_F3          = $86
KEY_F5          = $87
KEY_F7          = $88
KEY_F2          = $89
KEY_STOP        = $03
KEY_LEFT_ARROW  = $5f
KEY_A           = $41
KEY_SHIFT_A     = $c1
KEY_RETURN      = $0d
KEY_DEL         = $14
KEY_SPACE       = $20

screen          = $0400
status_row      = screen + 24*40
color_ram       = $d800
image_screen    = $4400
image_bitmap    = $6000
standalone_player = $0334
save_pointer    = $fb                   ; zeropage pointer for the KERNAL SAVE (music is stopped then)
copy_source     = $fb                   ; zeropage pointers for copy_pages (music is stopped then)
copy_target     = $fd
startup_stash   = $d000                 ; RAM under the I/O area: a copy of the startup code for F2

; Buffers in RAM the KERNAL does not use while the browser runs
request         = $0200                 ; WiC64 request header ("R", HTTP GET, URL length) ...
request_length  = $0202
request_url     = $0204                 ; ... and URL, up to $0258; the LOAD helper uses the same layout
c64_ip          = $02a7                 ; 16 bytes, only at startup
message         = $02a7                 ; 40 bytes
menu_ids        = $02cf                 ; 40 bytes: folder id of each entry, 0 = file

SECTION_PROGRAMS = 0
SECTION_PICTURES = 1
SECTION_MUSIC    = 2

LOCATION_MENU   = 0                     ; offsets in "locations"
LOCATION_TUNE   = 4

MODE_SAVE       = 1                     ; what download_program does with the program
MODE_RUN        = 2
MODE_HELPER     = 4                     ; install the LOAD helper, so the program can load more files

load_helper     = $0334                 ; LOAD helper (c64/loadhelper.asm), sent by the server
LOAD_VECTOR     = $0330

ADDRESS_ROW     = 5
ADDRESS_MAX     = 30                    ; max length of the "ip:port" server address

TIMEOUT         = $0f                   ; ~15 seconds, the server may need a moment to convert a picture
CHECK_TIMEOUT   = $02                   ; ~2 seconds for the background check for pushed programs
CHECK_BACKOFF   = 5                     ; seconds to wait after a failed check

;------------------------------------------------------------------------------
; BASIC stub: 2025 SYS2061, copies the program to $c000 and starts it
;------------------------------------------------------------------------------

* = $0801
    !word stub_end, 2025
    !byte $9e                           ; SYS
    !text "2061"
    !byte 0
stub_end:
    !word 0

    ldx #>(code_end - code_start + $ff) ; number of pages to copy
    ldy #0
stub_source = * + 1
-   lda code_image,y
stub_target = * + 1
    sta code_start,y
    iny
    bne -
    inc stub_source+1
    inc stub_target+1
    dex
    bne -
    jmp main

code_image:
!pseudopc $c000 {
code_start:

!macro status .message {
    lda #<.message
    ldy #>.message
    jsr show_status
}

;------------------------------------------------------------------------------
; Main loop: every key handler ends with jmp main_loop
;------------------------------------------------------------------------------

main_loop:
    jsr background_tasks
    jsr GETIN
    beq main_loop

    cmp #KEY_F1
    bne +
    lda #SECTION_PROGRAMS
    jmp open_section
+   cmp #KEY_F3
    bne +
    lda #SECTION_PICTURES
    jmp open_section
+   cmp #KEY_F5
    bne +
    lda #SECTION_MUSIC
    jmp open_section
+   cmp #KEY_F7
    beq +
    cmp #KEY_STOP
    bne ++
+   jsr stop_music
    jsr show_now_playing
    jmp main_loop
++  cmp #KEY_F2
    bne +
    jmp change_server
+   cmp #'+'
    beq next_page
    cmp #'-'
    beq previous_page
    cmp #KEY_DEL
    bne +
    jmp parent_folder
+   cmp #KEY_RETURN
    bne +
    jmp toggle_info
+   cmp #KEY_SPACE
    bne +
    jsr next_tune
    jmp main_loop
+   cmp #KEY_LEFT_ARROW
    bne +
    jmp enter_portal

    ; A-T opens an entry
+   cmp #KEY_A
    bcc +
    cmp #KEY_A+20
    bcs ++
    sbc #KEY_A-1                        ; carry is clear: subtract one less
    jsr select_entry
    jmp main_loop

    ; 1-9 selects a subtune
+   cmp #'1'
    bcc main_loop
    cmp #'9'+1
    bcs main_loop
    sbc #'1'-1                          ; carry is clear: subtract one less
    jsr select_subtune
ignore_key:
    jmp main_loop

    ; SHIFT+A-T saves a program to disk
++  cmp #KEY_SHIFT_A
    bcc ignore_key
    cmp #KEY_SHIFT_A+20
    bcs ignore_key
    sbc #KEY_SHIFT_A-1                  ; carry is clear: subtract one less
    jsr save_entry
    jmp main_loop

open_section:
    sta section
    lda #0
    sta folder
    sta folder+1
    sta page
    jsr load_menu
    jmp main_loop

next_page:
    lda page
    clc
    adc #1
    cmp menu_pages
    bcc +
    lda #0
+   sta page
    jsr load_menu
    jmp main_loop

previous_page:
    lda page
    bne +
    lda menu_pages
+   sec
    sbc #1
    sta page
    jsr load_menu
    jmp main_loop

parent_folder:
    lda menu_parent
    sta folder
    lda menu_parent+1
    sta folder+1
    lda #0
    sta page
    jsr load_menu
    jmp main_loop

toggle_info:
    lda info_shown
    bne +
    jsr show_info
    jmp main_loop
+   jsr load_menu
    jmp main_loop

; Opens entry A of the menu: a folder, or a program, picture or tune
select_entry:
    cmp menu_count
    bcs ++
    sta selected
    asl
    tax
    lda menu_ids,x
    ora menu_ids+1,x
    beq +
    lda menu_ids,x
    sta folder
    lda menu_ids+1,x
    sta folder+1
    lda #0
    sta page
    jmp load_menu

+   lda section
    cmp #SECTION_PICTURES
    bne +
    jmp show_picture
+   bcc +
    jmp play_selected_tune
+   lda #MODE_RUN | MODE_HELPER
    jmp download_entry
++  rts

; Saves program A of the menu to disk
save_entry:
    ldx section                         ; only programs, and not folders
    bne +
    cmp menu_count
    bcs +
    sta selected
    asl
    tax
    lda menu_ids,x
    ora menu_ids+1,x
    bne +
    lda #MODE_SAVE
    jmp download_entry
+   rts

;------------------------------------------------------------------------------
; F2: change the server address. The address screen is part of the startup code,
; which tunes and programs overwrite later; main keeps a copy of it in the RAM
; under the I/O area and it is copied back here.
;------------------------------------------------------------------------------

change_server:
    jsr stop_music                      ; the startup code comes back where a tune may be
    lda #<startup_stash
    sta copy_source
    lda #>startup_stash
    sta copy_source+1
    lda #<startup_start
    sta copy_target
    lda #>startup_start
    sta copy_target+1
    jsr copy_pages
    jsr restore_ui
    jsr ask_server_address
    jsr save_address
    lda #SECTION_PROGRAMS
    jmp open_section

; Copies the startup code's pages from copy_source to copy_target, with the RAM under the I/O area visible
copy_pages:
    sei
    lda #$34
    sta $01
    ldx #>(startup_end - startup_start + $ff)
    ldy #0
-   lda (copy_source),y
    sta (copy_target),y
    iny
    bne -
    inc copy_source+1
    inc copy_target+1
    dex
    bne -
    lda #$37
    sta $01
    cli
    rts

;------------------------------------------------------------------------------
; Background tasks: time display, auto-next and checking for pushed programs
;------------------------------------------------------------------------------

background_tasks:
    lda playing
    beq +
    lda seconds
    cmp shown_seconds
    beq +
    sta shown_seconds
    jsr draw_time
    lda minutes                         ; tune over? then play the next one
    cmp length_minutes
    bcc +
    bne ++
    lda seconds
    cmp length_seconds
    bcc +
++  jmp next_tune

+   lda $a2                             ; about once a second (jiffy clock)
    sec
    sbc last_check
    cmp #50
    bcc +
    lda polling
    beq +
    lda $a2
    sta last_check
    lda check_delay                     ; after a failed check, wait a few seconds
    beq check_push
    dec check_delay
+   rts

; Draws " m:ss/m:ss" (elapsed / length) at the end of the status line
draw_time:
    lda #' '
    sta status_row+30
    lda #':'
    sta status_row+32
    sta status_row+37
    lda #'/'
    sta status_row+35
    lda minutes
    and #$0f
    ora #'0'
    sta status_row+31
    lda length_minutes
    and #$0f
    ora #'0'
    sta status_row+36
    lda seconds
    ldx #33
    jsr +
    lda length_seconds
    ldx #38
+   pha
    lsr
    lsr
    lsr
    lsr
    ora #'0'
    sta status_row,x
    pla
    and #$0f
    ora #'0'
    sta status_row+1,x
    rts

; Asks the server whether a program was pushed. Timeouts and errors are silent here.
check_push:
    lda #'x'
    jsr url_begin
    lda #CHECK_TIMEOUT                  ; only for this request, the library restores the timeout
    sta wic64_timeout
    inc checking
    jsr start_request
    +wic64_receive push_state, 1        ; 0 = nothing, 1 = run, 2 = save and run, 3 = picture, 4 = tune
    +wic64_finalize
    dec checking
    lda push_state
    beq ++
    cmp #3
    bcs push_media
    lda #MODE_RUN | MODE_HELPER
    ldx push_state
    cpx #2
    bcc +
    lda #MODE_RUN | MODE_HELPER | MODE_SAVE
+   jsr prepare_download
    lda #'p'
    jsr url_begin_push
    jmp download_program
++  rts

push_media:
    beq +
    lda #'s'
    jsr url_begin_push
    jmp play_prepared_tune
+   lda #'i'
    jsr url_begin_push
    jmp show_prepared_picture

; url = server + "/x/" + A
url_begin_push:
    pha
    lda #'x'
    jsr url_begin
    lda #'/'
    jsr url_add
    pla
    jmp url_add

;------------------------------------------------------------------------------
; Menu: the server renders the whole screen, we only copy it to $0400
;------------------------------------------------------------------------------

load_menu:
    +status msg_loading
    lda #'m'
    jsr url_begin
    lda #'/'
    jsr url_add
    ldx section
    lda section_chars,x
    jsr url_add
    lda folder+1
    jsr url_add_slash_hex
    lda folder
    jsr url_add_hex
    lda page
    jsr url_add_slash_hex
    jsr start_request

    +wic64_receive menu_count, 4        ; entries, pages, parent folder
    +wic64_receive menu_ids, 40
    +wic64_receive screen, 1000
    +wic64_finalize

    lda #0
    sta info_shown
    lda #1
    sta polling
    jsr apply_colors
    jmp show_now_playing

;------------------------------------------------------------------------------
; Programs: received to their load address, then saved to disk and/or started.
; Everything below the browser is received here; a small starter in the stack
; page receives the rest (up to $cfff, over the browser) and starts the program.
;------------------------------------------------------------------------------

download_entry:
    jsr prepare_download
    lda #'p'
    ldx #LOCATION_MENU
    jsr url_begin_location
    jmp download_program

; Stops the music and fetches the LOAD helper if the mode asks for it. A = MODE_*
prepare_download:
    sta program_mode
    jsr stop_music                      ; the program may overwrite the tune
    +status msg_loading
    lda program_mode
    and #MODE_HELPER
    beq +
    lda #'h'
    jsr url_begin
    jsr start_request
    +wic64_receive $02a7, $0300 - $02a7
    +wic64_receive load_helper, $03fc - load_helper
    +wic64_finalize
+   rts

; Downloads the program of the prepared request
download_program:
    jsr start_request
    +wic64_receive program_name_length, 17
    lda #18                             ; status byte, name length, name
    bne receive_program

; The server fetches the WiC64 portal and sends it like any other program
enter_portal:
    lda #MODE_RUN
    jsr prepare_download
    lda #'o'
    jsr url_begin
    jmp download_program

receive_program:
    clc
    adc #2                              ; + load address
    sta program_prefix
    +wic64_receive program_load, 2

    ; end = load address + response size - prefix
    sec
    lda wic64_response_size
    sbc program_prefix
    tax
    lda wic64_response_size+1
    sbc #0
    tay
    txa
    clc
    adc program_load
    sta program_end
    tya
    adc program_load+1
    sta program_end+1

    ; receive up to $c000 now, the rest (tail) later from the starter
    lda #0
    sta tail_count
    sta tail_count+1
    lda program_end
    ldx program_end+1
    cpx #>code_start
    bcc +
    sta tail_count                      ; tail = end - $c000
    txa
    sbc #>code_start                    ; carry is set
    sta tail_count+1
    lda #<code_start
    ldx #>code_start
+   sec
    sbc program_load
    sta wic64_bytes_to_transfer
    txa
    sbc program_load+1
    sta wic64_bytes_to_transfer+1
    lda program_load
    sta wic64_response
    lda program_load+1
    sta wic64_response+1
    jsr wic64_receive

    lda tail_count
    ora tail_count+1
    beq +
    lda program_mode                    ; programs over the browser can only be started
    and #MODE_RUN
    bne start_program
    +wic64_finalize
    +status msg_too_large
    rts

+   +wic64_finalize
    lda program_mode
    and #MODE_SAVE
    beq +
    jsr save_program
    bcs ++                              ; do not start it when saving failed
+   lda program_mode
    and #MODE_RUN
    bne start_program
++  rts

; Hands over to the starter in the stack page
start_program:
    ldx #starter_end - starter_image - 1
-   lda starter_image,x
    sta starter,x
    dex
    bpl -

    lda program_mode
    and #MODE_HELPER
    beq +
    lda #'l'                            ; the LOAD helper's URL: "http://server/l/folder/" + file name
    jsr url_begin
    lda folder+1                        ; files are loaded from the folder the menu shows
    jsr url_add_slash_hex
    lda folder
    jsr url_add_hex
    lda #'/'
    jsr url_add
    lda url_length
    sta load_helper+3                   ; prefix_length
    lda #>load_helper
+   sta st_helper+1                     ; nonzero: install the helper

    lda tail_count
    sta st_count
    lda tail_count+1
    sta st_count+1
    lda program_end
    sta st_end+1
    lda program_end+1
    sta st_end_high+1
    lda program_load
    sta st_load
    lda program_load+1
    sta st_load+1
    sei
    jmp starter

starter_image:
!pseudopc $0100 {
starter:
    ldx #$ff
    txs

    ; receive the rest of the program, over the browser
st_receive:
    lda st_count
    ora st_count+1
    beq st_received
-   lda $dd0d
    and #$10
    beq -
    lda $dd01
st_store:
    sta code_start
    inc st_store+1
    bne +
    inc st_store+2
+   lda st_count
    bne +
    dec st_count+1
+   dec st_count
    jmp st_receive
st_received:
    lda #$00                            ; userport back to input, like wic64_finalize
    sta $dd03
    lda $dd0d

    ; start it in a freshly initialized machine
    lda #$37
    sta $01
    lda #0
    sta $c6                             ; empty keyboard buffer
    sta $0800                           ; BASIC needs a 0 in front of the program
    jsr IOINIT
    jsr RESTOR
    jsr CINT                            ; screen editor and VIC in power-on state
st_end:
    lda #0
    sta $2d                             ; end of BASIC program / start of variables
st_end_high:
    lda #0
    sta $2e
st_helper:
    lda #0
    beq +
    lda #<load_helper                   ; LOAD asks the server first
    sta LOAD_VECTOR
    lda #>load_helper
    sta LOAD_VECTOR+1
+   cli
    lda st_load+1
    cmp #$08                            ; loaded at $08xx: RUN it, otherwise jump to it
    bne +
    jsr BASIC_CLR
    jmp BASIC_RUN
+   jmp (st_load)

st_count:       !word 0
st_load:        !word 0
}
starter_end:

; Saves program_load-program_end to device 8 and shows the drive status. Carry set on error.
save_program:
    +status msg_saving
    lda #0
    sta $9d                             ; no KERNAL messages
    lda program_name_length
    ldx #<program_name
    ldy #>program_name
    jsr SETNAM
    lda #1
    ldx #8
    ldy #0
    jsr SETLFS
    lda program_load
    sta save_pointer
    lda program_load+1
    sta save_pointer+1
    lda #save_pointer
    ldx program_end
    ldy program_end+1
    jsr SAVE
    bcc +
    +status msg_no_drive
    sec
    rts

    ; read the drive status, e.g. "00, ok,00,00" or "63,file exists,00,00"
+   lda #0
    jsr SETNAM
    lda #15
    ldx #8
    ldy #15
    jsr SETLFS
    jsr OPEN
    ldx #15
    jsr CHKIN
    ldy #0
-   jsr CHRIN
    cmp #KEY_RETURN
    beq +
    jsr petscii_to_screen_code
    sta status_row,y
    iny
    lda $90                             ; end of file or error
    bne +
    cpy #40
    bne -
+   lda #' '
-   cpy #40
    beq +
    sta status_row,y
    iny
    bne -
+   jsr CLRCHN
    lda #15
    jsr CLOSE
    lda status_row                      ; status 00-19 are no errors
    cmp #'2'
    rts

;------------------------------------------------------------------------------
; Pictures: Koala data straight into VIC bank 1
;------------------------------------------------------------------------------

show_picture:
    lda #'i'
    ldx #LOCATION_MENU
    jsr url_begin_location

show_prepared_picture:
    lda playing
    beq +
    lda sid_flags
    and #$01                            ; would the picture overwrite the tune?
    beq +
    jsr stop_music

+   +status msg_loading
    jsr start_request

    +wic64_receive image_bitmap, 8000
    +wic64_receive image_screen, 1000
    +wic64_receive color_ram, 1000
    +wic64_receive image_background, 1
    +wic64_finalize

    lda #$00
    sta $d020
    lda image_background
    sta $d021
    lda $dd00
    and #%11111100
    ora #%00000010                      ; VIC bank 1: $4000-$7fff
    sta $dd00
    lda #$18                            ; screen at $4400, bitmap at $6000
    sta $d018
    lda #$18                            ; multicolor
    sta $d016
    lda #$3b                            ; bitmap mode
    sta $d011

-   jsr GETIN
    beq -

    jsr restore_ui
    jmp show_now_playing

;------------------------------------------------------------------------------
; Music: load the tune to its load address and play it from an interrupt
;------------------------------------------------------------------------------

play_selected_tune:
    ldx #LOCATION_MENU
    !byte $2c                           ; bit $xxxx: skips the next ldx
play_tune:
    ldx #LOCATION_TUNE
    lda #'s'
    jsr url_begin_location

play_prepared_tune:
    jsr stop_music
    +status msg_loading
    jsr start_request

    +wic64_receive sid_header, sid_header_end - sid_header
    ldx #3                              ; where the tune is, for the info screen and auto-next
-   lda sid_location,x
    sta locations + LOCATION_TUNE,x
    dex
    bpl -
    lda sid_flags
    and #$04                            ; tune needs the browser's memory or its own interrupts?
    beq +

    ; Standalone: the server sends a small player that receives the rest of the tune itself
    +wic64_receive standalone_player, $0400 - standalone_player
    ldx #39
-   lda now_playing,x                   ; "<name> - reset to return"
    sta status_row,x
    dex
    bpl -
    sei
    jmp standalone_player

+   lda sid_load
    sta wic64_response
    lda sid_load+1
    sta wic64_response+1
    +wic64_receive                      ; the rest of the response is the tune itself
    +wic64_finalize

    lda sid_start_song
    sta sid_song
    jsr start_music
    jmp show_now_playing

; SPACE or end of tune: play the next tune of the folder
next_tune:
    lda playing
    beq +
    lda sid_next_page
    sta tune_page
    lda sid_next_entry
    sta tune_entry
    jmp play_tune
+   rts

show_info:
    lda playing
    beq +
    +status msg_loading
    lda #'v'
    ldx #LOCATION_TUNE
    jsr url_begin_location
    jsr start_request
    +wic64_receive screen, 1000
    +wic64_finalize
    lda #0
    sta menu_count                      ; letters do nothing on the info screen
    lda #1
    sta info_shown
    jsr apply_colors
    jmp show_now_playing
+   rts

start_music:
    sei
    lda sid_bank
    sta $01
    lda sid_init
    sta init_call+1
    lda sid_init+1
    sta init_call+2
    lda sid_play
    sta play_call+1
    lda sid_play+1
    sta play_call+2

    lda #<music_irq
    sta $0314
    lda #>music_irq
    sta $0315

    lda sid_flags
    and #$02                            ; tune wants CIA timing: keep the CIA timer interrupt
    bne +

    lda #$7f                            ; otherwise play once per frame from a raster interrupt
    sta $dc0d
    lda $dc0d
    lda #$30
    sta $d012
    lda $d011
    and #$7f
    sta $d011
    lda #$01
    sta $d01a

+   lda #$ff
    sta $d019
    jsr init_tune
    lda #1
    sta playing
    cli
    rts

; Starts subtune sid_song and resets the clock to its length
init_tune:
    jsr silence_sid
    lda #0
    sta seconds
    sta minutes
    lda #$ff
    sta shown_seconds
    sta length_minutes                  ; unknown length: no auto-next
    sta length_seconds
    lda sid_fps
    sta ticks
    lda sid_song
    cmp #9
    bcs +
    asl
    tax
    lda sid_lengths,x
    sta length_minutes
    lda sid_lengths+1,x
    sta length_seconds
+   lda sid_song
    ldx #0
    ldy #0
init_call:
    jmp $ffff

music_irq:
    lda #$ff
    sta $d019
play_call:
    jsr $ffff

    ; count the playing time as BCD minutes and seconds
    dec ticks
    bne ++
    lda sid_fps
    sta ticks
    sed
    lda seconds
    clc
    adc #1
    cmp #$60
    bcc +
    lda minutes                         ; carry is set: add one minute
    adc #0
    sta minutes
    lda #0
+   sta seconds
    cld
++  jmp KERNAL_IRQ                      ; keyboard scan, acknowledges the CIA

stop_music:
    lda playing
    beq +
    sei
    lda #$00
    sta $d01a
    sta playing
    lda #$ff
    sta $d019
    lda #<KERNAL_IRQ
    sta $0314
    lda #>KERNAL_IRQ
    sta $0315
    lda #$25                            ; restore the default 60Hz KERNAL timer
    sta $dc04
    lda #$40
    sta $dc05
    lda #$11
    sta $dc0e
    lda #$81
    sta $dc0d
    lda $dc0d
    jsr silence_sid
    lda #$37
    sta $01
    cli
+   rts

select_subtune:
    ldx playing
    beq +
    cmp sid_songs
    bcs +
    sta sid_song
    sei
    jsr init_tune
    cli
+   rts

silence_sid:
    lda #0
    ldx #$18
-   sta $d400,x
    dex
    bpl -
    rts

;------------------------------------------------------------------------------
; HTTP requests
;------------------------------------------------------------------------------

; Sends the request and receives the status byte. Returns only on success.
start_request:
    jsr send_request
    +wic64_receive app_status, 1
    lda app_status
    bne +
    rts
+   +wic64_receive message, 40          ; the server explains what went wrong
    +wic64_finalize
    jmp show_error

send_request:
    lda #"R"
    sta request
    lda #WIC64_HTTP_GET
    sta request+1
    lda url_length
    sta request_length
    lda #0
    sta request_length+1
    +wic64_initialize
    +wic64_send_header request
    +wic64_send                         ; the URL follows the header
    +wic64_receive_header
    rts

; url = "http://" + server address + "/" + A
url_begin:
    pha
    ldx #0
-   lda url_scheme,x
    sta request_url,x
    inx
    cpx #url_scheme_end - url_scheme
    bne -
    stx url_length
    ldy #0
-   lda server_address,y
    jsr url_add                         ; preserves Y
    iny
    cpy address_length
    bne -
    lda #'/'
    jsr url_add
    pla
    jmp url_add

; url = server + "/" + A + "/" + folder + "/" + page + "/" + entry of location X
url_begin_location:
    stx url_location
    jsr url_begin
    ldx url_location
    lda locations+1,x
    jsr url_add_slash_hex
    ldx url_location
    lda locations,x
    jsr url_add_hex
    ldx url_location
    lda locations+2,x
    jsr url_add_slash_hex
    ldx url_location
    lda locations+3,x

url_add_slash_hex:
    pha
    lda #'/'
    jsr url_add
    pla

url_add_hex:
    pha
    lsr
    lsr
    lsr
    lsr
    jsr +
    pla
    and #$0f
+   cmp #10
    bcc +
    adc #'a'-'0'-10-1                   ; carry is set
+   adc #'0'

url_add:
    ldx url_length
    sta request_url,x
    inc url_length
    rts

;------------------------------------------------------------------------------
; Error handling
;------------------------------------------------------------------------------

on_timeout:
    jsr check_failed
    ldx #39
-   lda msg_timeout,x
    sta message,x
    dex
    bpl -
    bmi show_error

on_wic64_error:
    jsr check_failed
    +wic64_execute status_request, message  ; PETSCII, converted in place below
    ldx #0
-   lda message,x
    beq +
    jsr petscii_to_screen_code
    sta message,x
    inx
    cpx #40
    bne -
+   lda #' '
-   cpx #40
    beq show_error
    sta message,x
    inx
    bne -

; A failed background check (a slow network, the WiC64 reconnecting): no error, try again later
check_failed:
    lda checking
    beq +
    lda #0
    sta checking
    lda #CHECK_BACKOFF
    sta check_delay
    ldx main_stack
    txs
    jmp main_loop
+   rts

; Shows the 40 byte message in the status line and continues in the main loop
show_error:
    ldx main_stack
    txs
    lda #0
    sta checking
    +wic64_dont_disable_irqs
    jsr restore_ui
    ldx #39
-   lda message,x
    sta status_row,x
    lda #10                             ; light red
    sta color_ram + 24*40,x
    dex
    bpl -
    jmp main_loop

petscii_to_screen_code:
    cmp #$40
    bcc +++                             ; $20-$3f stay the same
    cmp #$60
    bcs +
    and #$3f                            ; $40-$5f -> $00-$1f
    rts
+   cmp #$80
    bcs +
    sbc #$20-1                          ; $60-$7f -> $40-$5f (carry is clear)
    rts
+   cmp #$c0
    bcc ++
    cmp #$e0
    bcs ++
    and #$7f                            ; $c0-$df -> $40-$5f
    rts
++  lda #' '
+++ rts

;------------------------------------------------------------------------------
; Screen
;------------------------------------------------------------------------------

restore_ui:
    lda #$1b
    sta $d011
    lda #$c8
    sta $d016
    lda #$17                            ; upper/lowercase character set
    sta $d018
    lda $dd00
    ora #%00000011                      ; VIC bank 0
    sta $dd00
    lda #$00
    sta $d020
    sta $d021
    lda #$80                            ; disable shift+C= charset switching
    sta $0291
    ; fall through

apply_colors:
    ldx #0
    lda #15                             ; light grey
-   sta color_ram,x
    sta color_ram+$100,x
    sta color_ram+$200,x
    sta color_ram+$2e8,x
    inx
    bne -

    ldx #39
-   lda #3                              ; title: cyan
    sta color_ram,x
    lda #1                              ; status line: white
    sta color_ram + 24*40,x
    lda #12                             ; help: grey
    sta color_ram + 22*40,x
    sta color_ram + 23*40,x
    dex
    bpl -

    lda #<(color_ram + 2*40 + 1)        ; entry letters: yellow (rows 2-21, column 1)
    sta letter_color+1
    lda #>(color_ram + 2*40 + 1)
    sta letter_color+2
    ldx #20
-   lda #7
letter_color:
    sta $ffff
    lda letter_color+1
    clc
    adc #40
    sta letter_color+1
    bcc +
    inc letter_color+2
+   dex
    bne -
    rts

clear_screen:
    ldx #0
    lda #' '
-   sta screen,x
    sta screen+$100,x
    sta screen+$200,x
    sta screen+$2e8,x
    inx
    bne -
    rts

; Shows the screen code string at A/Y (terminated by $ff) in the status line, padded with spaces
show_status:
    sta status_source+1
    sty status_source+2
    ldx #0
status_source:
-   lda $ffff,x
    cmp #$ff
    beq +
    sta status_row,x
    inx
    cpx #40
    bne -
    rts
+   lda #' '
-   sta status_row,x
    inx
    cpx #40
    bne -
    rts

show_now_playing:
    ldx #39
-   lda #' '
    ldy playing
    beq +
    lda now_playing,x
+   sta status_row,x
    lda #1
    sta color_ram + 24*40,x
    dex
    bpl -
    lda #$ff                            ; redraw the time
    sta shown_seconds
    rts

;------------------------------------------------------------------------------
; Data
;------------------------------------------------------------------------------

section_chars:  !text "pis"

url_scheme:     !text "http://"
url_scheme_end:


; The server address can be edited at startup, the default comes from the Makefile
server_address: +server_address_text    ; e.g. "192.168.1.10:6464"
server_address_default_end:
!if server_address_default_end - server_address > ADDRESS_MAX {
    !error "default server address is too long"
}
                !fill ADDRESS_MAX - (server_address_default_end - server_address), 0
address_length: !byte server_address_default_end - server_address

status_request: !byte "R", WIC64_GET_STATUS_MESSAGE, $01, $00, $00


msg_loading:            !scr "Loading...", $ff
msg_saving:             !scr "Saving to disk...", $ff
msg_too_large:          !scr "Too large to save", $ff
msg_no_drive:           !scr "Save failed - no drive 8?", $ff
msg_timeout:            !scr "Timeout: is the server on? F2 = address"
                        !fill 40 - (* - msg_timeout), ' '

main_stack:     !byte 0
url_length:     !byte 0
url_location:   !byte 0
section:        !byte 0
locations:
folder:         !word 0                 ; LOCATION_MENU: what the menu shows
page:           !byte 0
selected:       !byte 0
tune_folder:    !word 0                 ; LOCATION_TUNE: the tune that plays
tune_page:      !byte 0
tune_entry:     !byte 0
menu_count:     !byte 0                 ; received together: entries, pages, parent folder
menu_pages:     !byte 1
menu_parent:    !word 0
info_shown:     !byte 0
polling:        !byte 0                 ; check for pushed programs
checking:       !byte 0                 ; a background check is running
check_delay:    !byte 0                 ; checks to skip after a failed one
last_check:     !byte 0
push_state:     !byte 0
app_status:     !byte 0
image_background: !byte 0
program_mode:   !byte 0
program_prefix: !byte 0
program_load:   !word 0
program_end:    !word 0
tail_count:     !word 0
program_name_length: !byte 0            ; received together with program_name
program_name:   !fill 16, 0
playing:        !byte 0
sid_song:       !byte 0
ticks:          !byte 0
seconds:        !byte 0                 ; BCD
minutes:        !byte 0                 ; BCD
shown_seconds:  !byte 0
length_minutes: !byte 0                 ; BCD length of the subtune
length_seconds: !byte 0

; Received from the server in one go, see SidService.Response
sid_header:
sid_load:       !word 0
sid_end:        !word 0
sid_init:       !word 0
sid_play:       !word 0
sid_songs:      !byte 0
sid_start_song: !byte 0
sid_bank:       !byte 0
sid_flags:      !byte 0                 ; bit 0: overlaps picture memory, bit 1: CIA timing, bit 2: standalone
sid_fps:        !byte 0                 ; interrupts per second
sid_next_page:  !byte 0
sid_next_entry: !byte 0
sid_lengths:    !fill 18, 0             ; subtunes 1-9: BCD minutes, BCD seconds
sid_location:   !fill 4, 0              ; folder, page, entry of this tune
now_playing:    !fill 40, ' '
sid_header_end:

!src "wic64.asm"

code_end:
}

;------------------------------------------------------------------------------
; Startup code: only runs once, right after the copy to $c000, so it stays
; where the program was loaded instead of taking space at $c000
;------------------------------------------------------------------------------

;------------------------------------------------------------------------------
; Startup
;------------------------------------------------------------------------------

startup_start:
main:
    lda #$37
    sta $01
    jsr restore_ui
    jsr clear_screen

    +status msg_detecting
    +wic64_detect
    bcc +
    +status msg_no_device
    rts
+   beq +
    +status msg_legacy_firmware
    rts

+   jsr ask_server_address
    jsr save_address

    ; keep a copy of this startup code for F2 (change the server address)
    lda #<startup_start
    sta copy_source
    lda #>startup_start
    sta copy_source+1
    lda #<startup_stash
    sta copy_target
    lda #>startup_stash
    sta copy_target+1
    jsr copy_pages

    +wic64_set_timeout TIMEOUT
    +wic64_dont_disable_irqs            ; keep the music playing during transfers

    ; Timeouts and errors jump to these handlers with the stack reset to this level
    tsx
    stx main_stack
    +wic64_set_timeout_handler on_timeout
    +wic64_set_error_handler on_wic64_error

    lda #SECTION_PROGRAMS
    jmp open_section

;------------------------------------------------------------------------------
; Startup screen: edit the proposed server address, RETURN accepts it
;------------------------------------------------------------------------------

ask_server_address:
    lda #0                              ; F2 later: a failing request here must not jump to the menu
    sta wic64_handlers_suspended
    jsr clear_screen
    lda #<msg_title
    ldy #>msg_title
    ldx #0
    jsr print_row
    lda #<msg_enter_address
    ldy #>msg_enter_address
    ldx #3
    jsr print_row
    lda #<msg_address_help
    ldy #>msg_address_help
    ldx #8
    jsr print_row
    +status msg_empty

    ; propose the address that worked last time, if it is on the disk
    jsr load_saved_address
    lda address_loaded
    beq +
    +status msg_address_loaded
+
    ; show the C64's own address, handy to check both are on the same network
    +wic64_execute ip_request, c64_ip
    bcs edit_address
    bne edit_address
    lda #<msg_this_c64
    ldy #>msg_this_c64
    ldx #11
    jsr print_row
    ldx #0
-   lda c64_ip,x
    beq edit_address
    sta screen + 11*40 + 10,x           ; digits and dots are the same in ASCII and screen codes
    inx
    cpx #15
    bne -

edit_address:
    ldx #ADDRESS_MAX
    lda #1                              ; white input field
-   sta color_ram + ADDRESS_ROW*40 + 2,x
    dex
    bpl -

edit_address_loop:
    jsr draw_address
-   jsr GETIN
    beq -

    cmp #KEY_RETURN
    bne +
    lda address_length
    beq edit_address_loop
    lda #1                              ; the timeout and error handlers work again
    sta wic64_handlers_suspended
    rts

+   cmp #KEY_DEL
    bne +
    lda address_length
    beq edit_address_loop
    dec address_length
    inc address_changed
    jmp edit_address_loop

    ; accept 0-9 . : - and letters (for host names)
+   ldx address_length
    cpx #ADDRESS_MAX
    bcs edit_address_loop
    cmp #'-'
    beq add_address_char
    cmp #'.'
    beq add_address_char
    cmp #'0'
    bcc edit_address_loop
    cmp #':'+1
    bcc add_address_char
    cmp #KEY_A
    bcc edit_address_loop
    cmp #KEY_A+26
    bcs edit_address_loop
    ora #$20                            ; PETSCII letter -> ASCII lowercase
add_address_char:
    sta server_address,x
    inc address_length
    inc address_changed
    jmp edit_address_loop

; Shows the address (ASCII) as screen codes with a reverse space as cursor
draw_address:
    ldx #0
draw_address_char:
    cpx address_length
    bcs draw_address_cursor
    lda server_address,x
    cmp #$60
    bcc +
    sbc #$60                            ; ASCII lowercase -> screen code
+   jmp draw_address_store
draw_address_cursor:
    lda #' '
    cpx address_length
    bne draw_address_store              ; past the cursor: space
    lda #$a0                            ; cursor: reverse space
draw_address_store:
    sta screen + ADDRESS_ROW*40 + 2,x
    inx
    cpx #ADDRESS_MAX+1
    bne draw_address_char
    rts

;------------------------------------------------------------------------------
; The address is remembered in the SEQ file "WIC64 SERVER" on device 8.
; Without a drive or disk nothing happens: the built-in address is proposed.
;------------------------------------------------------------------------------

address_file    = 2                     ; logical file number
saved_address   = $0340                 ; tape buffer, free while the browser starts

load_saved_address:
    lda #0
    sta $9d                             ; no KERNAL messages
    sta file_index
    lda #read_name_end - read_name
    ldx #<read_name
    ldy #>read_name
    jsr open_address_file
    bcs close_address_file
    ldx #address_file
    jsr CHKIN
    bcs close_address_file

-   jsr CHRIN
    cmp #KEY_RETURN                     ; end of the line (also what a missing file gives)
    beq ++
    jsr is_address_char
    bcs close_address_file              ; not an address: ignore the file
    ldx file_index
    sta saved_address,x
    inc file_index
    lda $90                             ; end of file or error
    bne ++
    cpx #ADDRESS_MAX-1
    bcc -

++  ldx file_index
    beq close_address_file
    stx address_length
-   dex
    lda saved_address,x
    sta server_address,x
    txa
    bne -
    inc address_loaded

close_address_file:
    jsr CLRCHN
    lda #address_file
    jmp CLOSE

; Saves the address when it was changed or was not on the disk yet
save_address:
    lda address_loaded
    beq +
    lda address_changed
    beq ++
+   +status msg_saving_address
    lda #0
    sta $9d
    sta file_index

    ; delete the old file ("S:WIC64 SERVER" on the command channel)
    lda #scratch_name_end - scratch_name
    ldx #<scratch_name
    ldy #>scratch_name
    jsr SETNAM
    lda #15
    ldx #8
    ldy #15
    jsr SETLFS
    jsr OPEN
    php
    lda #15
    jsr CLOSE
    plp
    bcs ++                              ; no drive

    lda #write_name_end - write_name
    ldx #<write_name
    ldy #>write_name
    jsr open_address_file
    bcs close_address_file
    ldx #address_file
    jsr CHKOUT
    bcs close_address_file
-   ldx file_index
    lda server_address,x
    jsr CHROUT
    inc file_index
    lda file_index
    cmp address_length
    bne -
    lda #KEY_RETURN
    jsr CHROUT
    jmp close_address_file
++  rts

; A/X/Y: file name for SETNAM. Opens it as logical file 2 on device 8, carry set on error.
open_address_file:
    jsr SETNAM
    lda #address_file
    ldx #8
    ldy #address_file
    jsr SETLFS
    jmp OPEN

; Carry clear if A is a character of an address: - . 0-9 : A-Z a-z
is_address_char:
    cmp #'-'
    beq +
    cmp #'.'
    beq +
    cmp #'0'
    bcc ++
    cmp #':'+1
    bcc +
    cmp #'A'
    bcc ++
    cmp #'Z'+1
    bcc +
    cmp #'a'
    bcc ++
    cmp #'z'+1
    bcc +
++  sec
    rts
+   clc
    rts

read_name:      !text "WIC64 SERVER,S,R"
read_name_end:
write_name:     !text "WIC64 SERVER,S,W"
write_name_end:
scratch_name:   !text "S:WIC64 SERVER"
scratch_name_end:

file_index:     !byte 0
address_loaded: !byte 0
address_changed: !byte 0

ip_request:     !byte "R", WIC64_GET_IP, $00, $00

msg_title:              !scrxor $80, " WiC64 Browser"
                        !fill 40 - (* - msg_title), $a0
                        !byte $ff
msg_enter_address:      !scr "Server address (IP or name:port):", $ff
msg_address_help:       !scr "RETURN = connect    DEL = erase", $ff
msg_this_c64:           !scr "This C64: ", $ff
msg_address_loaded:     !scr "Last used address, loaded from disk", $ff
msg_saving_address:     !scr "Saving the address on disk...", $ff
msg_empty:              !byte $ff
msg_detecting:          !scr "Looking for the WiC64...", $ff
msg_no_device:          !scr "No WiC64 found (or it does not respond)", $ff
msg_legacy_firmware:    !scr "Please update the WiC64 to firmware 2.x", $ff

;------------------------------------------------------------------------------
; Startup only: print a screen code string in any row
;------------------------------------------------------------------------------

; Prints the screen code string at A/Y (terminated by $ff) in row X, padded with spaces
print_row:
    sta print_source+1
    sty print_source+2
    lda row_low,x
    sta print_target+1
    sta print_pad_target+1
    lda row_high,x
    sta print_target+2
    sta print_pad_target+2
    ldx #0
print_source:
-   lda $ffff,x
    cmp #$ff
    beq +
print_target:
    sta $ffff,x
    inx
    cpx #40
    bne -
    rts
+   lda #' '
print_pad_target:
-   sta $ffff,x
    inx
    cpx #40
    bne -
    rts

row_low:
!for row, 0, 24 {
    !byte <(screen + row*40)
}
row_high:
!for row, 0, 24 {
    !byte >(screen + row*40)
}

startup_end:

!if startup_end - startup_start > $1000 {
    !error "the startup code does not fit in the RAM under the I/O area"
}


!if code_end > $d000 {
    !error "program does not fit in $c000-$cfff"
}
